name: Check Source Branch

on:
  push:
  pull_request:
    branches:
      - QA
      - master
      - development

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dfx
        uses: dfinity/setup-dfx@main

      - name: Deploy to development
        if: github.base_ref == 'development'
        run: |
          echo ${{ secrets.CATALYZE_DEVELOPMENT }} | base64 --decode > catalyze_development.pem
          dfx identity import --storage-mode=plaintext catalyze_development catalyze_development.pem
          bash scripts/generate.sh
          dfx canister install parent --network ic --wasm wasm/parent.wasm.gz --mode upgrade

      - name: Check source for QA
        if: github.base_ref == 'QA'
        run: |
          if [[ "${{ github.head_ref }}" != "development" ]]; then
            echo "Only changes from the development branch can be merged into QA."
            exit 1
          fi

      - name: Check source for master
        if: github.base_ref == 'master'
        run: |
          if [[ "${{ github.head_ref }}" == "QA" ]]; then
            echo "Only changes from the QA branch can be merged into master."
            exit 1
          fi
